name: Build and install package

on:
    #push:
    #    branches:
    #        - main
    #pull_request:
    #    branches:
    #        - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest] #[ubuntu-latest, windows-latest, macos-latest]
                python-version: ["3.10-dev"] #["3.8", "3.11"]
        
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip setuptools wheel pytest
            
            - name: Build package and install through pip
              run: |
                  python -m pip install .

            - name: List installed files
              run: |
                  ls C:\hostedtoolcache\windows\Python\3.11.6\x64\Lib\site-packages\pybind_experiments

            - name: Run tests
              run: |
                  cd ..
                  python -m pytest -v pybind-experiments/tests/test_imports.py --ignore=build --cache-clear
                  python -m pytest -v pybind-experiments/tests/test_sum.py --ignore=build --cache-clear
