name: Test

on:
    # trigger on all commits to main
    push:
        branches:
            - main

    # trigger on pull requests to main
    pull_request:
        branches:
            - main

    # trigger on request
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: ["3.8-dev", "3.11-dev"]
        
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  pip install --upgrade pip setuptools wheel pytest
            
            - name: Build package and install through pip
              run: |
                  pip install --verbose .

            - name: Run tests
              run: |
                  pytest -v
