name: Test GPU

on:
    # trigger on all commits to main
    #push:
    #    branches:
    #        - main

    # trigger on pull requests to main
    #pull_request:
    #    branches:
    #        - main

    # trigger on request
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                python-version: ["3.8-dev"]
                cuda: ["12.1"]
        
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Set up CUDA
              # if: contains(matrix.os, 'ubuntu')
              env:
                cuda: ${{ matrix.cuda }}
              run: .github/action_scripts/install-cuda-ubuntu.sh
              shell: bash

            - name: Install dependencies
              run: |
                  pip install --upgrade pip setuptools wheel pytest
            
            - name: Build package and install through pip
              env:
                  ENABLE_GPU: ON
              run: |
                  pip install --verbose .

            # we cannot really test without a GPU
            # so we only check the import from command line
            - name: Run test import
              run: |
                  python -c 'import pybind_experiments'
